### PR TITLE
Added support for multiple points for source of motion

### PR DESCRIPTION
**Pull request by tm1990**
Adds support for multiple points when using motion detection.
It has a range and max variable to be able to decrease/increase the amount of points that are detected

Since without this you can only get one accurate position at a time when detecting motion this will allow to look for multiple positions at the same time.

Someelse should probably look through this since i am not too experienced in java and specially not in this area but it seems to be working from what i have tested.

### CODE REVIEW

**Comment by sarxos** [comment]
Hi @tm1990,

Thank you for the pull request. This is very nice and well done feature! I had some low priority comments in regards to the code and it would be great if you can address them when you have some time (especially example demonstrating multiple points detection use case would be very helpful for the users).

Please let me know if you like to add changes to this pull request or shall I merge this one and you will craft second one for the fixes.

**Comment by tm1990** [comment]
I can make those changes and add them to this one a little bit later today when i have some free time.

**Comment by sarxos** [comment]
Ok, thank you!

**Comment by tm1990** [comment]
Added a small example for the multi-point motion detection. Probably terrible but that is at least what i was trying to create when i made the multi point changes
Also change the points variable to lower-case
And for the space/tabs thing is there any specific areas to which i have used spaces that you could see? At least from what i saw i think i have use tabs

**Comment by sarxos** [comment]
@tm1990,

The problem with tabs is probably caused by your IDE which is converting them to spaces, but don't worry - this is not blocking and I can convert them later to the appropriate ones.

Thank you!

**Comment by tm1990** [comment]
Ok i will look at that in case i have to make any other pull requests here.
And no problem. Glad i could actuly help.

**Pull request merged**
