### PR TITLE
raspberrypi raspistill driver

### PR DESCRIPTION
**Pull request by alexmao86**
Hi yuripourre,

Please review my pull as we discussed before.

thanks,
Anping Mao

### CODE REVIEW

**Comment by meesawsabba** [comment]
~Waseem~

**Comment by alexmao86** [comment]
dissatisfied with myself, emmm....

**Comment by yuripourre** [comment]
@alexmao86, I saw you closed this PR too, what happened?
I made some comments in the other PR trying to help somehow, but I didn't intent to discourage you.

About this PR, it is too big to review but I would be glad to do so if you open it again.

Would you mind to try to submit a smaller PR?
I saw you included even an PNGDecoder, what if you tried raspiyuv instead of raspistill driver (this way, it would be possible to convert directly from RGB to BufferedImage)?

**Comment by alexmao86** [comment]
Hi yuripourre,
I am not a skilled git user, so I am not sure my way of request merge is OK or not. actually, I meant to close this request and reopen one because I changed subproject name from driver-raspistill to driver-raspberrypi.
Please check my request [#694](https://github.com/sarxos/webcam-capture/pull/694).

Raspiberrypi provided，
- raspistill: output encoded image can be PNG, bmp, jpeg
- raspistillyuv, :output can be rgb24 or yuv422
- raspividyuv  :output can be rgb24 or yuv422
- raspiyuv. :output can be rgb24 or yuv422
I wrapped all of them as drivers. and also convert direct from rgb to BufferedImage. the performance is really good, for raspividyuv  and raspiyuv, the fps can be synchronized with raspiyuv -fps settings. and CPU loading is not high, I tested.

thanks,
Alex

**Comment by sarxos** [comment]
Hello @alexmao86,

As @yuripourre stated, this pull request contain too many commits to review all of them. To simplify things a little bit I squashed all changes from  #694 into a single commit and merged into the master as https://github.com/sarxos/webcam-capture/commit/78c58cb3d0da8d6c94550d46827d49259c6bbd2e.

I would like to ask you to review again if you have a time and provide comments directly in 78c58cb3d0da8d6c94550d46827d49259c6bbd2e. We can then work them out one by one.

Just for your information, @alexmao86, you can use `git commit --amend` to _append_ new changes, or changes from review, to an existing commit (as long as you are the commit author). By doing it this way you will not generate so many commits in a single pull request. The code review will also be simpler. Please see more details in:

- https://nathanhoad.net/git-amend-your-last-commit
- https://pl.atlassian.com/git/tutorials/rewriting-history

**Pull request closed without merging**
