### PR TITLE
Address MacOS Catalina no webcam found issue 

### PR DESCRIPTION
**Pull request by kkieffer**
This PR attempts to address the issue in #723 

The updated .dylib is from 1.4-SNAPSHOT of OpenIMAJ.  The author has addressed in the issues in Catalina where it is necessary to ask the user's permission to access the camera.  The OpenIMAJGrabber is updated to reflect changes in the native interface.

I have tested this now on Catalina and it does detect all connected webcams.  However there is a problem trying to open the session from java, this error occurs:

This app has crashed because it has a hardened runtime and attempted to access privacy-sensitive data without an entitlement indicating its intent to access this data.  The app must have the 'com.apple.security.device.camera' entitlement.

I suspect if you package your java program into an .app with the correct entitlements it will work.  I haven't tried this because OpenJDK 14 has some trouble with jpackage right now.

### CODE REVIEW

**Comment by sarxos** [comment]
Hi @kkieffer, 

Thank you for this PR. I took a brief look at the `dylib` file and it seems to differ from the one in OpenIMAJ:

I downloaded `dylib` from your PR and from OpenIMAJ master (1.4-SNAPSHOT):

* webcam-capture/src/main/resources/com/github/sarxos/webcam/ds/buildin/lib/darwin_universal/libOpenIMAJGrabber.dylib
* openimaj/raw/master/hardware/core-video-capture/src/main/resources/org/openimaj/video/capture/nativelib/darwin_universal/libOpenIMAJGrabber.dylib

In bash:

```plain
$ wget https://github.com/sarxos/webcam-capture/raw/4ead2cf3d848007dff8a0df53a3c2b39e538b0b2/webcam-capture/src/main/resources/com/github/sarxos/webcam/ds/buildin/lib/darwin_universal/libOpenIMAJGrabber.dylib -O libOpenIMAJGrabber.dylib.1
$ wget https://github.com/openimaj/openimaj/raw/master/hardware/core-video-capture/src/main/resources/org/openimaj/video/capture/nativelib/darwin_universal/libOpenIMAJGrabber.dylib -O libOpenIMAJGrabber.dylib.2
```

Then calculate md5 sum:

```plain
$ md5sum libOpenIMAJGrabber.dylib.1 libOpenIMAJGrabber.dylib.2
46cc65680d3932f3d395676aef782c6e  libOpenIMAJGrabber.dylib.1
d72965a6298c1f95b0b5cb66bc691c26  libOpenIMAJGrabber.dylib.2
```

As you can see these files are different. Did you compile it on your own or maybe committed wrong one?

**Comment by kkieffer** [comment]
I built the dylib from the Xcode project in openimaj.  Probably, it signed it with my cert instead.

**Comment by sarxos** [comment]
@kkieffer But is there any reason to build it? There is already compiled re-distributable file in OpenIMAJ. I would prefer it to be taken from there since OpenIMAJ version is more mature and tested. It's also smaller in size.

**Comment by sarxos** [comment]
@kkieffer If there is no valid reason to have it compiled, then can you put the OpenIMAJ's file version in this PR, amend commit and push it with --force? Or should I do it?

```
$ git add libOpenIMAJGrabber.dylib
$ git commit --amend
$ git push origin HEAD:master --force
```

**Comment by kkieffer** [comment]
I updated with dylib from openimaj.  Note however this is not signed. I fear, to use this library on Catalina, one will have to unpack the jar, sign the dylib, and repack the jar. Apple does not make it easy on Catalina.

**Comment by kkieffer** [comment]
Oh I checked the openimaj library works the same as the one I built

**Comment by sarxos** [comment]
@kkieffer That is great. Ok then, I merging your PR. Thank you once again!

**Pull request merged**
